name: Build android apk

on:
  push:
    branches: ["*",]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
    
      - name: Build debug apk
        run: ./gradlew assembleDebug
    
      - uses: actions/upload-artifact@v4
        with: 
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      